### ISSUE TITLE
데이터베이스 커넥션 에러

### ISSUE THREAD

**Issue by kimyonghyeon82** [SexyTreeTrunks/dw-java-project#5]
```
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4056)
	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4025)
	at user_tbl.UserDAO.getUsers(UserDAO.java:118)
	at user_tbl.test.main(test.java:45)

```

테스트 도중 오류가 생기는데 db에는 들어감

**Comment by treetrunks2** [comment]
get connection함수에서 conn==null 체크를 제거하여 해결
```
private Connection getConnection() {
	//	if (conn == null) {
			String user = "root";
			String passwd = "dwclass7"; // 달라진부분
			String unicode = "autoReconnect=true&characterEncoding=UTF-8";
			String url = "jdbc:mysql://35.190.228.94:3306/teamdb?";//
			try {
				Class.forName("com.mysql.jdbc.Driver");
				conn = DriverManager.getConnection(url + unicode, user, passwd);
			} catch (Exception e) {
				e.printStackTrace();
			}
	//	}
		return conn;
	}
```
